
bg = "%base00"
input_bg = "%base01"
input_color = "%base07" 
input_focused_bg = "%base02"
input_focused_border = "%base0E"
input_focused_color = "%base04" 
input_focused_border_color = "%base01"
inner_box_bg = "%base02" 
inner_box_flowchild_bg = "%base02"
inner_box_flowchild_focused_bg = "%base00"
outer_box_bg = "%base01"
text_bg = "%base02"
text = "%base04"
scroll = "%base0D"

# base00 = "#2E3440"
# base01 = "#3B4252"
# base02 = "#434C5E"
# base03 = "#4C566A"
# base04 = "#D8DEE9"
# base05 = "#E5E9F0"
# base06 = "#ECEFF4"
# base07 = "#8FBCBB"
# base08 = "#BF616A"
# base09 = "#D08770"
# base0A = "#EBCB8B"
# base0B = "#A3BE8C"
# base0C = "#88C0D0"
# base0D = "#81A1C1"
# base0E = "#B48EAD"
# base0F = "#5E81AC"
