# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "git/config"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
vars = [ "bombadil/vars.toml" ]
prehooks = [
    "zsh -c \"mkdir -p ~/.tmux/plugins ~/.local/bin\""
]

[settings.dots]
# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
# sway = { source = "sway", target = ".config/sway" }
kitty = { source = "kitty", target = ".config/kitty"}
nvim = { source = "nvim", target = ".config/nvim"}
zshrc = { source = "zsh/zshrc", target = ".zshrc" }
zshprofile = { source = "zsh/zshprofile", target = ".zsh_profile" }
zshplugins = {source = "zsh/zshplugins.zsh", target = ".zshplugins"}
tmuxrc = { source = "tmux/tmux.conf", target = ".tmux.conf"}
tmux_sessionizer = { source = "tmux/tmux-sessionizer", target = ".local/bin/tmux-sessionizer" }
tmux_windowizer = { source = "tmux/tmux-windowizer", target = ".local/bin/tmux-windowizer" }
tmux_cht = { source = 'tmux/tmux-cht.sh', target = ".local/bin/tmux-cht.sh" }
tmux_tpm = { source = 'tmux/tpm', target = ".tmux/plugins/tpm" }
tmux_ta = { source = "tmux/ta", target = ".local/bin/ta" }
# You can have as many dot entry as you want, linking files or directories
# alacritty = { source = "alacritty", target = ".config/alacritty/alacritty.yml" }

[[import]]
path = "sway/sway.toml"
