#!/usr/bin/env fish

function setup_space -a idx name
  set space
  echo "setting up space $idx : $name"
  
  if not yabai -m query --spaces --space $idx >/dev/null 2>&1;

    yabai -m space --create
  end
  yabai -m space $idx --label $name
end

# Workaround to fix M1 support (short term)
sudo yabai --load-sa

# Setup Signals
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/setup_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/setup_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# bar settings hack to get different paddings per display
yabai -m config external_bar all:42:0

# global settings
yabai -m config window_border		     on
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.15
yabai -m config window_shadow                float

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_animation_duration    0.15
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Border coloring
yabai -m config window_border_width	     2
yabai -m config window_border_radius	     11
yabai -m config active_window_border_color   0xffe1e3e4
yabai -m config normal_window_border_color   0xff2a2f38
yabai -m config insert_feedback_color        0xff9dd274

# Mouse support
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action	     swap

# general space settings
yabai -m config top_padding 		     20
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   8

# ===== Rules =====
# Do not manage some apps which are not resizable
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add label="Finder" app='^Finder$' title='(Co(py|nnect)|Move|Info|Pref)' manage=off
yabai -m rule --add label="Alfred" app='^Alfred$' manage=off

yabai -m rule --add label="System Preferences" app='^System Preferences$' manage=off
yabai -m rule --add label="App Store" app='^App Store$' manage=off
yabai -m rule --add label="Activity Monitor" app='^Activity Monitor$' manage=off
yabai -m rule --add label="Calculator" app='^Calculator$' manage=off
yabai -m rule --add label="Dictionary" app='^Dictionary$' manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# float Better Touch Tool Preference window
yabai -m rule --add title='^BetterTouchTool' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# float VPN UI
yabai -m rule --add title='Cisco AnyConnect*' manage=off

yabai -m rule --add app='^IntelliJ$' space=^1
yabai -m rule --add app='^Firefox$' space=^2
yabai -m rule --add app='^Microsoft Outlook$' space=3
yabai -m rule --add app='^Kitty$' space=5
yabai -m rule --add app='^Amazon Chime$' space=4
yabai -m rule --add app='^Slack$' space=6
yabai -m rule --add app='^Spotify$' space=7
yabai -m rule --add app='^Quip$' space=8
yabai -m rule --add app='^Microsoft Excel$' space=8

# Cleanup excess spaces on startup
for space in $(yabai -m query --spaces | jq '.[].index | select(. > 8)')
  yabai -m space --destroy 9
end

# Create my spaces
setup_space 1 Code
setup_space 2 Browser
setup_space 3 Mail
setup_space 4 Chime
setup_space 5 Terminal
setup_space 6 Chat
setup_space 7 Music
setup_space 8 Docs

yabai -m config layout                       float
echo "yabai configuration loaded.."


