#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/work ~/git ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

standup_session() {
    (TMUX=''
     tmux new-session -Ad -s "$selected_name" -c $selected;
     tmux split-window -vb -t "$selected_name" -c $selected -p 70;
     tmux send-keys -t "$selected_name" "nvim" Enter;
    )
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t $selected_name 2> /dev/null; then
#    tmux new-session -ds $selected_name -c $selected
    standup_session;
fi

tmux switch-client -t $selected_name
