
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Clone zcomet if necessary
if [[ ! -f ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh ]]; then
  command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi

# Plugins {{{
# source "${HOME}/.zshplugins"
source ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh
    zcomet load ohmyzsh
    zcomet load ohmyzsh plugins/asdf
    zcomet load ohmyzsh plugins/colored-man-pages
    zcomet load ohmyzsh plugins/cp
    zcomet load ohmyzsh plugins/git
    zcomet load ohmyzsh plugins/gpg-agent
    zcomet load ohmyzsh plugins/jsontools
    zcomet load ohmyzsh plugins/nmap
    zcomet load ohmyzsh plugins/npm
    zcomet load ohmyzsh plugins/rsync
    zcomet load ohmyzsh plugins/ssh-agent

    zcomet load sampson-chen/sack
    zcomet load zsh-users/zsh-syntax-highlighting
    zcomet load zsh-users/zsh-autosuggestions
    zcomet load supercrabtree/k
    zcomet load romkatv/powerlevel10k
    zcomet load dracula/zsh
    zcomet compinit

# Load the plugin manager
if ! true; then
    echo "Creating zgenom save"
    zgenom ohmyzsh
    zgenom ohmyzsh plugins/asdf
    zgenom ohmyzsh plugins/cp
    zgenom ohmyzsh plugins/git
    zgenom ohmyzsh plugins/gpg-agent
    zgenom ohmyzsh plugins/jsontools
    zgenom ohmyzsh plugins/nmap
    zgenom ohmyzsh plugins/npm
    zgenom ohmyzsh plugins/rsync
    zgenom ohmyzsh plugins/ssh-agent

    zgenom load sampson-chen/sack
    zgenom load zsh-users/zsh-syntax-highlighting
    zgenom load romkatv/powerlevel10k
    zgenom load dracula/zsh

    zgenom save
    zgenom compile "$HOME/.zshrc "
fi

# }}}
source $HOME/.zsh_profile

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
