# base00 = "#2E3440"
# base01 = "#3B4252"
# base02 = "#434C5E"
# base03 = "#4C566A"
# base04 = "#D8DEE9"
# base05 = "#E5E9F0"
# base06 = "#ECEFF4"
# base07 = "#8FBCBB"
# base08 = "#BF616A"
# base09 = "#D08770"
# base0A = "#EBCB8B"
# base0B = "#A3BE8C"
# base0C = "#88C0D0"
# base0D = "#81A1C1"
# base0E = "#B48EAD"
# base0F = "#5E81AC"
main_text_color = "%base05"
border_color = "%base0C"
bar_urgent = "%base08"
workspaces_fg = "%base05"
worspace_bg = "%base01"
worspace_focused_bg = "%base07"
bar_clock_bg = "%base0D"
bar_clock_fg = "%base05"
battery_bg = "%base0D"
battery_fg = "%base05"
battery_charging_bg = "%base0D"

battery_charging_fg = "%base05"
battery_critical_not_charging_fg= "%base05"
battery_critical_not_charging_bg="%base08"
blink_bg = "%base05"
blink_fg = "%base00"
label_focused = "%base00"
network_bg = "%base0C"
network_disconnected = "%base09"
pulse_audio_bg = "%base0D"
pulse_audio_fg = "%base05"
pulse_audio_muted_bg = "%base07"
tray_bg = "%base0D"
idle_inibitor_bg = "%base0D"
idle_inibitor_bg_activated = "%base04"